create table
  public.customer_cart (
    cart_id bigint generated by default as identity,
    customer character varying null,
    quantity bigint null,
    payment bigint null,
    price bigint null,
    constraint user_cart_pkey primary key (cart_id)
  ) tablespace pg_default;

create table
  public.catalog (
    sku character varying not null,
    name character varying not null,
    quantity bigint null,
    price bigint null,
    potion_type bigint null,
    constraint catalog_pkey primary key (sku)
  ) tablespace pg_default;

create table
  public.global_inventory (
    num_red_potions integer generated by default as identity,
    num_red_ml integer not null,
    gold integer not null,
    num_blue_potions integer not null,
    num_blue_ml integer not null,
    num_green_potions integer not null,
    num_green_ml integer not null,
    constraint global_inventory_pkey primary key (
      num_red_ml,
      gold,
      num_blue_ml,
      num_green_potions,
      num_green_ml,
      num_red_potions,
      num_blue_potions
    )
  ) tablespace pg_default;

create table
  public.account_ledger_entries (
    id bigint generated by default as identity,
    account_id bigint not null,
    account_transactions_id bigint null,
    change bigint null,
    customer_name text null,
    item_sku text null,
    constraint account_ledger_entries_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.account_transactions (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    description text null,
    constraint account_transactions_pkey primary key (id)
  ) tablespace pg_default;
